name: coi_pipeline #Name of the workflow

on:
  pull_request: 
    branches: [master]
# On which events this workflow should be triggered. We can use this as an array as well

# on: [push, pull_request, issue]

# We can specify events like this as well
# on:
#   pull_request:
#     types: [opened, closed, reopened]

jobs:
    _Code_Scanning:         # Name of the job 1
        runs-on: 
          - ubuntu-latest       # Selecting a GitHub Hosted Runner (Here selected a windows machine)
        defaults:
          run:
            working-directory: package.json
        steps:
        - uses: actions/checkout@v2
        - run:  echo "package json script"
        - run: test_script

    _Code_Build:              # Name of the job 2
        runs-on: 
          - ubuntu-latest       # Selecting a GitHub Hosted Runner (Here selected a windows machine)
        needs: ["_Code_Scanning"]  # If we want to run the first job before triggering the this job, we can set 'needs'
        steps:
            - uses: actions/setup-node@v2
              with:
                node-version: '10'
            - run: npm install -g mbt
            - run: mbt -v
                                
    _Code_Deploy:  
        runs-on: 
          - ubuntu-latest       # Selecting a GitHub Hosted Runner (Here selected a windows machine)
        needs: ["_Code_Build","_Docker_Image_build"]  # If we want to run the first job before triggering the this job, we can set 'needs'
        steps:
            - name: Echo the Directory
              run: echo "deploy phase"
              
    _Docker_Image_build:
        runs-on: 
          - ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: |
                  echo "docker build"
                  docker build . --file Dockerfile --tag docker.io
                  
                          
